version: "3.9"
services:
  web:
    image: webapp:latest
    build: .
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    networks:
      - webnet

networks:
  webnet:
